using System.Text;
using StripKit.Models;

namespace StripKit.Services;

/// <summary>
/// Emits ready-to-paste loader code for an exported filmstrip. Every snippet uses the same
/// universal frame-selection rule — <c>frame = clamp(round(value·(N−1)), 0, N−1)</c> — and the
/// source rectangle that matches the strip's stack direction. Pure string generation; the only
/// I/O is <see cref="SaveAsync"/>.
/// </summary>
public sealed class CodeSnippetService : ICodeSnippetService
{
    public string Generate(CodeTarget target, CodeSnippetRequest request) => target switch
    {
        CodeTarget.Juce => Juce(request),
        CodeTarget.Css => Css(request),
        CodeTarget.IPlug2 => IPlug2(request),
        CodeTarget.Hise => Hise(request),
        CodeTarget.React => React(request),
        _ => throw new ArgumentOutOfRangeException(nameof(target), target, "Unknown code target."),
    };

    public string FileName(CodeTarget target, string controlId)
    {
        var id = FileBase(controlId);
        return target switch
        {
            CodeTarget.Juce => $"{id}.juce.h",
            CodeTarget.Css => $"{id}.html",
            CodeTarget.IPlug2 => $"{id}.iplug2.cpp",
            CodeTarget.Hise => $"{id}.hise.js",
            CodeTarget.React => $"{id}.jsx",
            _ => throw new ArgumentOutOfRangeException(nameof(target), target, "Unknown code target."),
        };
    }

    public async Task<string> SaveAsync(CodeTarget target, CodeSnippetRequest request, string directory)
    {
        if (!string.IsNullOrEmpty(directory))
            Directory.CreateDirectory(directory);
        var path = Path.Combine(directory, FileName(target, request.ControlId));
        await File.WriteAllTextAsync(path, Generate(target, request));
        return path;
    }

    // ---- JUCE ----

    private static string Juce(CodeSnippetRequest r)
    {
        string pascal = Pascal(r.ControlId);
        string bin = BinaryDataName(r.AssetFileName);
        string stack = r.FramesAreHorizontal ? "horizontal" : "vertical";
        string sx = r.FramesAreHorizontal ? "frame * frameW" : "0";
        string sy = r.FramesAreHorizontal ? "0" : "frame * frameH";
        string hidpi = r.Asset2xFileName is null ? "" : $"\n// HiDPI: also ship {r.Asset2xFileName} and load it on 2x displays.";

        if (r.ComponentType == ComponentType.Meter)
        {
            return $$"""
                // {{pascal}}Meter.h — generated by StripKit (https://stripkit.pro)
                // Filmstrip: {{r.AssetFileName}} — {{r.FrameCount}} frames, {{r.FrameWidth}}x{{r.FrameHeight}} px each, {{stack}} stack.{{hidpi}}
                // A meter Component: call setLevel(0..1) from your audio/UI timer.
                #pragma once

                #include <juce_gui_basics/juce_gui_basics.h>
                #include <cmath>

                class {{pascal}}Meter : public juce::Component
                {
                public:
                    {{pascal}}Meter()
                    {
                        // Embedded via the Projucer/CMake BinaryData (recommended). Alternatively:
                        //   filmStrip = juce::ImageFileFormat::loadFrom (juce::File ("{{r.AssetFileName}}"));
                        filmStrip = juce::ImageCache::getFromMemory (BinaryData::{{bin}}, BinaryData::{{bin}}Size);
                    }

                    void setLevel (float newLevel /* 0..1 */)
                    {
                        level = juce::jlimit (0.0f, 1.0f, newLevel);
                        repaint();
                    }

                    void paint (juce::Graphics& g) override
                    {
                        const int frames = {{r.FrameCount}};
                        const int frameW = {{r.FrameWidth}};
                        const int frameH = {{r.FrameHeight}};
                        const int frame  = juce::jlimit (0, frames - 1, (int) std::lround (level * (frames - 1)));

                        g.drawImage (filmStrip, 0, 0, getWidth(), getHeight(),
                                     {{sx}}, {{sy}}, frameW, frameH);
                    }

                private:
                    juce::Image filmStrip;
                    float level = 0.0f;
                };
                """;
        }

        if (r.ComponentType is ComponentType.Button or ComponentType.Toggle)
        {
            string typeWord = r.ComponentType == ComponentType.Toggle ? "Toggle" : "Button";
            return $$"""
                // {{pascal}}{{typeWord}}.h — generated by StripKit (https://stripkit.pro)
                // Filmstrip: {{r.AssetFileName}} — {{r.FrameCount}} frames, {{r.FrameWidth}}x{{r.FrameHeight}} px each, {{stack}} stack.{{hidpi}}
                // Frame 0 = off, Frame 1 = on.  A latching toggle (setClickingTogglesState); for a momentary
                // button drive the frame from isButtonDown instead.
                #pragma once

                #include <juce_gui_basics/juce_gui_basics.h>

                class {{pascal}}{{typeWord}} : public juce::Button
                {
                public:
                    {{pascal}}{{typeWord}}() : juce::Button ("")
                    {
                        // Embedded via the Projucer/CMake BinaryData (recommended). Alternatively:
                        //   filmStrip = juce::ImageFileFormat::loadFrom (juce::File ("{{r.AssetFileName}}"));
                        filmStrip = juce::ImageCache::getFromMemory (BinaryData::{{bin}}, BinaryData::{{bin}}Size);
                        setClickingTogglesState (true);
                    }

                    void paintButton (juce::Graphics& g, bool /*isMouseOver*/, bool /*isButtonDown*/) override
                    {
                        const int frameW = {{r.FrameWidth}};
                        const int frameH = {{r.FrameHeight}};
                        const int frame  = getToggleState() ? 1 : 0;
                        const int {{(r.FramesAreHorizontal ? "sx" : "sy")}} = frame * {{(r.FramesAreHorizontal ? "frameW" : "frameH")}};

                        g.drawImage (filmStrip, 0, 0, getWidth(), getHeight(),
                                     {{sx}}, {{sy}}, frameW, frameH);
                    }

                private:
                    juce::Image filmStrip;
                };
                """;
        }

        if (r.ComponentType == ComponentType.RotaryKnob)
        {
            return $$"""
                // {{pascal}}LookAndFeel.h — generated by StripKit (https://stripkit.pro)
                // Filmstrip: {{r.AssetFileName}} — {{r.FrameCount}} frames, {{r.FrameWidth}}x{{r.FrameHeight}} px each, {{stack}} stack.{{hidpi}}
                // Assign to your Slider: slider.setLookAndFeel (&lnf); use a RotaryHorizontalVerticalDrag style.
                #pragma once

                #include <juce_gui_basics/juce_gui_basics.h>
                #include <cmath>

                class {{pascal}}LookAndFeel : public juce::LookAndFeel_V4
                {
                public:
                    {{pascal}}LookAndFeel()
                    {
                        // Embedded via the Projucer/CMake BinaryData (recommended). Alternatively:
                        //   filmStrip = juce::ImageFileFormat::loadFrom (juce::File ("{{r.AssetFileName}}"));
                        filmStrip = juce::ImageCache::getFromMemory (BinaryData::{{bin}}, BinaryData::{{bin}}Size);
                    }

                    void drawRotarySlider (juce::Graphics& g, int x, int y, int width, int height,
                                           float sliderPosProportional, float, float, juce::Slider&) override
                    {
                        const int frames = {{r.FrameCount}};
                        const int frameW = {{r.FrameWidth}};
                        const int frameH = {{r.FrameHeight}};
                        const int frame  = juce::jlimit (0, frames - 1,
                                              (int) std::lround (sliderPosProportional * (frames - 1)));

                        g.drawImage (filmStrip, x, y, width, height,
                                     {{sx}}, {{sy}}, frameW, frameH);   // source frame, {{stack}} stack
                    }

                private:
                    juce::Image filmStrip;
                };
                """;
        }

        // Vertical fader / horizontal slider.
        return $$"""
            // {{pascal}}LookAndFeel.h — generated by StripKit (https://stripkit.pro)
            // Filmstrip: {{r.AssetFileName}} — {{r.FrameCount}} frames, {{r.FrameWidth}}x{{r.FrameHeight}} px each, {{stack}} stack.{{hidpi}}
            // Assign to your Slider: slider.setLookAndFeel (&lnf); use a Linear* style.
            #pragma once

            #include <juce_gui_basics/juce_gui_basics.h>
            #include <cmath>

            class {{pascal}}LookAndFeel : public juce::LookAndFeel_V4
            {
            public:
                {{pascal}}LookAndFeel()
                {
                    // Embedded via the Projucer/CMake BinaryData (recommended). Alternatively:
                    //   filmStrip = juce::ImageFileFormat::loadFrom (juce::File ("{{r.AssetFileName}}"));
                    filmStrip = juce::ImageCache::getFromMemory (BinaryData::{{bin}}, BinaryData::{{bin}}Size);
                }

                void drawLinearSlider (juce::Graphics& g, int x, int y, int width, int height,
                                       float, float, float, juce::Slider::SliderStyle, juce::Slider& slider) override
                {
                    const int frames = {{r.FrameCount}};
                    const int frameW = {{r.FrameWidth}};
                    const int frameH = {{r.FrameHeight}};
                    const double prop = slider.valueToProportionOfLength (slider.getValue());
                    const int frame   = juce::jlimit (0, frames - 1, (int) std::lround (prop * (frames - 1)));

                    g.drawImage (filmStrip, x, y, width, height,
                                 {{sx}}, {{sy}}, frameW, frameH);   // source frame, {{stack}} stack
                }

            private:
                juce::Image filmStrip;
            };
            """;
    }

    // ---- CSS / HTML ----

    private static string Css(CodeSnippetRequest r)
    {
        string cls = CssClass(r.ControlId);
        string pascal = Pascal(r.ControlId);
        string stack = r.FramesAreHorizontal ? "horizontal" : "vertical";
        // Step one frame along the stack axis per --frame.
        string bgPos = r.FramesAreHorizontal
            ? $"calc(var(--frame, 0) * -{r.FrameWidth}px) 0"
            : $"0 calc(var(--frame, 0) * -{r.FrameHeight}px)";
        // Total strip size at 1x, so an @2x image scales down to it.
        string size1x = r.FramesAreHorizontal
            ? $"{r.FrameWidth * r.FrameCount}px {r.FrameHeight}px"
            : $"{r.FrameWidth}px {r.FrameHeight * r.FrameCount}px";

        string hidpi = r.Asset2xFileName is null ? "" : $$"""

            @media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) {
              .{{cls}} {
                background-image: url("{{r.Asset2xFileName}}");
                background-size: {{size1x}};
              }
            }
            """;

        return $$"""
            <!-- {{r.ControlId}} — generated by StripKit (https://stripkit.pro) -->
            <!-- Filmstrip: {{r.AssetFileName}} — {{r.FrameCount}} frames, {{r.FrameWidth}}x{{r.FrameHeight}} px each, {{stack}} stack. -->
            <style>
            .{{cls}} {
              width: {{r.FrameWidth}}px;
              height: {{r.FrameHeight}}px;
              background-image: url("{{r.AssetFileName}}");
              background-repeat: no-repeat;
              /* Pick the frame by setting --frame to 0..{{r.FrameCount - 1}} (see set{{pascal}} below). */
              background-position: {{bgPos}};
            }
            {{hidpi}}
            </style>

            <div class="{{cls}}" id="{{cls}}"></div>

            <script>
            // Map a 0..1 parameter value to the matching frame.
            function set{{pascal}}(el, value) {
              const frames = {{r.FrameCount}};
              const frame = Math.max(0, Math.min(frames - 1, Math.round(value * (frames - 1))));
              el.style.setProperty('--frame', frame);
            }
            // Demo: sweep it. (For autoplay instead, a CSS @keyframes with steps({{r.FrameCount}}) also works.)
            // let v = 0; setInterval(() => { v = (v + 0.01) % 1; set{{pascal}}(document.getElementById('{{cls}}'), v); }, 16);
            </script>
            """;
    }

    // ---- iPlug2 ----

    private static string IPlug2(CodeSnippetRequest r)
    {
        string id = Identifier(r.ControlId);
        string param = Pascal(r.ParameterId);
        string bitmapId = Identifier(r.ControlId).ToUpperInvariant() + "_FN";
        string stack = r.FramesAreHorizontal ? "horizontal" : "vertical";
        string horiz = r.FramesAreHorizontal ? "true" : "false";

        string attach = r.ComponentType switch
        {
            ComponentType.RotaryKnob =>
                $"pGraphics->AttachControl(new IBKnobControl(bounds, {id}Bitmap, k{param}));",
            ComponentType.VerticalFader =>
                $"pGraphics->AttachControl(new IBSliderControl(bounds, {id}Bitmap, k{param}, EDirection::Vertical));",
            ComponentType.HorizontalSlider =>
                $"pGraphics->AttachControl(new IBSliderControl(bounds, {id}Bitmap, k{param}, EDirection::Horizontal));",
            ComponentType.Button or ComponentType.Toggle =>
                $"pGraphics->AttachControl(new IBSwitchControl(bounds, {id}Bitmap, k{param}));  // toggle; frame 0 = off, frame 1 = on",
            _ =>   // Meter: a bitmap control whose frame follows its value (drive it from the DSP).
                $"pGraphics->AttachControl(new IBitmapControl(bounds, {id}Bitmap, k{param}));  // drive via a meter sender / SetValueFromDelegate",
        };

        return $$"""
            // {{r.ControlId}} — generated by StripKit (https://stripkit.pro)
            // Filmstrip: {{r.AssetFileName}} — {{r.FrameCount}} frames, {{r.FrameWidth}}x{{r.FrameHeight}} px each, frames {{stack}}.
            //
            // 1) Add {{r.AssetFileName}} to your project's resources and register it, e.g. in config.h / resources:
            //      #define {{bitmapId}} "{{r.AssetFileName}}"
            // 2) In your editor layout (mLayoutFunc / OnReset), inside the IGraphics setup:

            const IBitmap {{id}}Bitmap = pGraphics->LoadBitmap({{bitmapId}}, {{r.FrameCount}} /* nStates */, {{horiz}} /* framesAreHorizontal */);
            {{attach}}
            """;
    }

    // ---- HISE ----

    private static string Hise(CodeSnippetRequest r)
    {
        string id = Identifier(r.ControlId);
        string consts = id.ToUpperInvariant();
        string stack = r.FramesAreHorizontal ? "horizontal" : "vertical";
        string ox = r.FramesAreHorizontal ? $"frame * {r.FrameWidth}" : "0";
        string oy = r.FramesAreHorizontal ? "0" : $"frame * {r.FrameHeight}";

        return $$"""
            // {{r.ControlId}} — generated by StripKit (https://stripkit.pro)
            // Filmstrip: {{r.AssetFileName}} — {{r.FrameCount}} frames, {{r.FrameWidth}}x{{r.FrameHeight}} px each, {{stack}} stack.
            // Put {{r.AssetFileName}} in your project's Images folder.

            const var {{id}} = Content.addPanel("{{id}}", 0, 0);
            {{id}}.set("width", {{r.FrameWidth}});
            {{id}}.set("height", {{r.FrameHeight}});
            {{id}}.set("min", 0.0);
            {{id}}.set("max", 1.0);
            {{id}}.loadImage("{PROJECT_FOLDER}{{r.AssetFileName}}", "filmstrip");

            const var {{consts}}_FRAMES = {{r.FrameCount}};

            {{id}}.setPaintRoutine(function(g)
            {
                var v = this.getValue();   // 0..1
                var frame = Math.round(v * ({{consts}}_FRAMES - 1));
                g.drawImage("filmstrip", [0, 0, {{r.FrameWidth}}, {{r.FrameHeight}}], {{ox}}, {{oy}});
            });

            {{id}}.setControlCallback(function(component, value)
            {
                component.repaint();
            });
            """;
    }

    // ---- React (web / WebView GUIs) ----

    private static string React(CodeSnippetRequest r)
    {
        string pascal = Pascal(r.ControlId);
        string stack = r.FramesAreHorizontal ? "horizontal" : "vertical";
        string horiz = r.FramesAreHorizontal ? "true" : "false";
        string hidpi = r.Asset2xFileName is null ? ""
            : $"\n// HiDPI: also ship {r.Asset2xFileName}; set backgroundSize to the 1x strip size and switch by devicePixelRatio.";

        return $$"""
            // {{pascal}}.jsx — generated by StripKit (https://stripkit.pro)
            // Filmstrip: {{r.AssetFileName}} — {{r.FrameCount}} frames, {{r.FrameWidth}}x{{r.FrameHeight}} px each, {{stack}} stack.{{hidpi}}
            import React from 'react';

            const FRAMES = {{r.FrameCount}};
            const FRAME_W = {{r.FrameWidth}};
            const FRAME_H = {{r.FrameHeight}};
            const HORIZONTAL = {{horiz}};

            // value: a 0..1 parameter value -> the matching filmstrip frame.
            export default function {{pascal}}({ value = 0, className, style }) {
              const frame = Math.max(0, Math.min(FRAMES - 1, Math.round(value * (FRAMES - 1))));
              const backgroundPosition = HORIZONTAL ? `${-frame * FRAME_W}px 0` : `0 ${-frame * FRAME_H}px`;
              const spriteStyle = {
                width: FRAME_W,
                height: FRAME_H,
                backgroundImage: `url("{{r.AssetFileName}}")`,
                backgroundRepeat: 'no-repeat',
                backgroundPosition,
                ...style,
              };
              return <div className={className} style={spriteStyle} />;
            }
            // Usage: <{{pascal}} value={0.5} />
            """;
    }

    // ---- identifier helpers ----

    /// <summary>A valid C/JS identifier: non-alphanumerics → '_', never leads with a digit.</summary>
    private static string Identifier(string s)
    {
        var sb = new StringBuilder(s.Length);
        foreach (char c in s)
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        string id = sb.ToString().Trim('_');
        if (id.Length == 0) return "control";
        return char.IsDigit(id[0]) ? "_" + id : id;
    }

    /// <summary>PascalCase across word boundaries (non-alphanumerics), for class / param names.</summary>
    private static string Pascal(string s)
    {
        var sb = new StringBuilder(s.Length);
        bool nextUpper = true;
        foreach (char c in s)
        {
            if (char.IsLetterOrDigit(c))
            {
                sb.Append(nextUpper ? char.ToUpperInvariant(c) : c);
                nextUpper = false;
            }
            else
            {
                nextUpper = true;
            }
        }
        string p = sb.ToString();
        if (p.Length == 0) return "Control";
        return char.IsDigit(p[0]) ? "_" + p : p;
    }

    /// <summary>A valid CSS class: lowercase, non-alphanumerics → '-', leads with a letter.</summary>
    private static string CssClass(string s)
    {
        var sb = new StringBuilder(s.Length);
        foreach (char c in s.ToLowerInvariant())
            sb.Append(char.IsLetterOrDigit(c) ? c : '-');
        string cls = string.Join('-', sb.ToString().Split('-', StringSplitOptions.RemoveEmptyEntries));
        if (cls.Length == 0) return "sk-control";
        return char.IsLetter(cls[0]) ? cls : "sk-" + cls;
    }

    /// <summary>JUCE BinaryData mangling of a file name: each non-alphanumeric → '_'.</summary>
    private static string BinaryDataName(string fileName)
    {
        var sb = new StringBuilder(fileName.Length);
        foreach (char c in fileName)
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        string n = sb.ToString();
        if (n.Length == 0) return "asset_png";
        return char.IsDigit(n[0]) ? "_" + n : n;
    }

    /// <summary>A filesystem-safe base name for the emitted snippet file.</summary>
    private static string FileBase(string controlId)
    {
        var invalid = Path.GetInvalidFileNameChars();
        var sb = new StringBuilder(controlId.Length);
        foreach (char c in controlId)
            sb.Append(Array.IndexOf(invalid, c) >= 0 || c == ' ' ? '_' : c);
        string b = sb.ToString().Trim();
        return b.Length == 0 ? "control" : b;
    }
}
