using System.Globalization;
using System.Text;
using System.Text.Json;
using StripKit.Models;

namespace StripKit.Services;

/// <summary>
/// Emits offline-render recipes (Blender <c>bpy</c> / CSV / JSON) that make a path-traced frame
/// sequence match StripKit's runtime law — <c>angle_i = start + (end − start)·i/(N−1)</c>, the
/// same <c>(N−1)</c> divisor the renderer uses so the last frame lands exactly on the max. The
/// angle convention matches the app: 0° = 12 o'clock (pointer up), positive = clockwise on
/// screen. Pure string generation, mirroring <see cref="CodeSnippetService"/>; the only I/O is
/// <see cref="SaveAsync"/>.
/// </summary>
public sealed class RenderRecipeService : IRenderRecipeService
{
    public string Generate(RenderRecipeTarget target, RenderRecipeRequest request) => target switch
    {
        RenderRecipeTarget.Blender => Blender(request),
        RenderRecipeTarget.Csv => Csv(request),
        RenderRecipeTarget.Json => Json(request),
        _ => throw new ArgumentOutOfRangeException(nameof(target), target, "Unknown recipe target."),
    };

    public string FileName(RenderRecipeTarget target, string controlId)
    {
        var id = FileBase(controlId);
        return target switch
        {
            RenderRecipeTarget.Blender => $"{id}.blender.py",
            RenderRecipeTarget.Csv => $"{id}.frames.csv",
            RenderRecipeTarget.Json => $"{id}.frames.json",
            _ => throw new ArgumentOutOfRangeException(nameof(target), target, "Unknown recipe target."),
        };
    }

    public async Task<string> SaveAsync(RenderRecipeTarget target, RenderRecipeRequest request, string directory)
    {
        if (!string.IsNullOrEmpty(directory))
            Directory.CreateDirectory(directory);
        var path = Path.Combine(directory, FileName(target, request.ControlId));
        await File.WriteAllTextAsync(path, Generate(target, request));
        return path;
    }

    /// <summary>
    /// The per-frame table the recipe is built from: for each filmstrip frame <c>i</c> (0..N−1),
    /// its normalized value <c>t = i/(N−1)</c> and — for a rotary knob — the absolute rotation
    /// <c>start + (end − start)·t</c>. This is the single source of truth all three targets share,
    /// and it mirrors <c>SkiaFilmstripRenderer.ComputeTransform</c> exactly.
    /// </summary>
    public static IReadOnlyList<RecipeFrame> BuildFrameTable(RenderRecipeRequest r)
    {
        int n = Math.Max(1, r.FrameCount);
        var rows = new List<RecipeFrame>(n);
        for (int i = 0; i < n; i++)
        {
            double t = n > 1 ? (double)i / (n - 1) : 0.0;
            double angle = r.IsRotary ? r.StartAngleDegrees + (r.EndAngleDegrees - r.StartAngleDegrees) * t : 0.0;
            rows.Add(new RecipeFrame(i, t, angle));
        }
        return rows;
    }

    // ---- Blender ----

    private static string Blender(RenderRecipeRequest r)
    {
        var ci = CultureInfo.InvariantCulture;
        int n = Math.Max(1, r.FrameCount);
        string start = r.StartAngleDegrees.ToString("0.######", ci);
        string end = r.EndAngleDegrees.ToString("0.######", ci);
        string isRotary = r.IsRotary ? "True" : "False";
        string what = r.IsRotary
            ? "a rotary knob (the body is rotated by angle_i on each frame)"
            : $"a {r.ComponentType} value-driven sequence (drive your rig from the baked 0..1 \"value\" property)";

        // $$""" => holes are {{...}}, single braces are literal. The Python below deliberately uses
        // no curly braces (no dicts / f-strings), so nothing here needs escaping.
        return $$"""
            # {{r.ControlId}} render recipe — generated by StripKit (https://stripkit.pro)
            # Renders {{n}} frames of {{what}} so they stack into a StripKit filmstrip.
            #
            # StripKit frame law:  angle_i = START_DEG + (END_DEG - START_DEG) * i/(N-1)
            # The (N-1) divisor lands the last frame exactly on the max. Angle convention:
            # 0 deg = 12 o'clock (pointer up); positive = clockwise on screen. Model the knob
            # with its pointer at 12 o'clock (the 0 deg pose); the script rotates from there.
            #
            # HOW TO USE
            #   1. Open your scene; set OBJECT_NAME to the control object and SPIN_AXIS to the
            #      axis facing the camera. If it spins the wrong way, flip SPIN_SIGN to -1.0.
            #   2. Run this (Scripting > Run Script, or:  blender file.blend -b -P this.py -a).
            #   3. A keyframe is baked on every frame (exact angles, no interpolation drift) plus a
            #      0..1 "value" custom property you can drive non-rotary rigs from with drivers.
            #   4. Render the animation, then in StripKit > Assemble point at the frames/ folder.

            import bpy, math

            # ---- CONFIG (edit these) ----
            OBJECT_NAME = "Knob"   # the object to animate
            SPIN_AXIS   = "Z"      # "X" / "Y" / "Z" — the axis pointing at the camera
            SPIN_SIGN   = 1.0      # set to -1.0 if the knob rotates the wrong way

            # ---- StripKit recipe (generated; matches the runtime law) ----
            N         = {{n}}
            START_DEG = {{start}}
            END_DEG   = {{end}}
            RES_X     = {{r.FrameWidth}}
            RES_Y     = {{r.FrameHeight}}
            IS_ROTARY = {{isRotary}}

            scene = bpy.context.scene
            scene.render.film_transparent = True
            scene.render.image_settings.file_format = "PNG"
            scene.render.image_settings.color_mode  = "RGBA"
            scene.render.resolution_x = RES_X
            scene.render.resolution_y = RES_Y
            scene.render.resolution_percentage = 100
            scene.frame_start = 1
            scene.frame_end   = N

            obj = bpy.data.objects.get(OBJECT_NAME)
            if obj is None:
                raise SystemExit("StripKit recipe: object '" + OBJECT_NAME + "' not found - set OBJECT_NAME.")

            axis = "XYZ".index(SPIN_AXIS)
            if IS_ROTARY:
                obj.rotation_mode = "XYZ"

            for i in range(N):
                t = i / (N - 1) if N > 1 else 0.0
                scene.frame_set(i + 1)
                obj["value"] = t
                obj.keyframe_insert(data_path='["value"]')
                if IS_ROTARY:
                    angle = START_DEG + (END_DEG - START_DEG) * t
                    obj.rotation_euler[axis] = math.radians(SPIN_SIGN * angle)
                    obj.keyframe_insert(data_path="rotation_euler", index=axis)

            # Writes frame_0001.png .. (RGBA, transparent) into the .blend folder's frames/ subfolder.
            scene.render.filepath = "//frames/frame_"
            bpy.ops.render.render(animation=True)
            """;
    }

    // ---- CSV ----

    private static string Csv(RenderRecipeRequest r)
    {
        var ci = CultureInfo.InvariantCulture;
        var sb = new StringBuilder();
        sb.Append("frame,value,angle_deg\n");
        foreach (var f in BuildFrameTable(r))
            sb.Append(f.Frame.ToString(ci)).Append(',')
              .Append(f.Value.ToString("0.000000", ci)).Append(',')
              .Append(f.AngleDegrees.ToString("0.0000", ci)).Append('\n');
        return sb.ToString();
    }

    // ---- JSON ----

    private static string Json(RenderRecipeRequest r)
    {
        var doc = new
        {
            generator = "StripKit",
            url = "https://stripkit.pro",
            controlId = r.ControlId,
            componentType = r.ComponentType.ToString(),
            frameCount = Math.Max(1, r.FrameCount),
            law = "angle_i = startAngleDegrees + (endAngleDegrees - startAngleDegrees) * i / (frameCount - 1)",
            angleConvention = "0 deg = 12 o'clock (pointer up); positive = clockwise (screen space)",
            startAngleDegrees = r.IsRotary ? r.StartAngleDegrees : 0.0,
            endAngleDegrees = r.IsRotary ? r.EndAngleDegrees : 0.0,
            resolution = new { width = r.FrameWidth, height = r.FrameHeight },
            frames = BuildFrameTable(r).Select(f => new
            {
                frame = f.Frame,
                value = Math.Round(f.Value, 6),
                angleDeg = Math.Round(f.AngleDegrees, 4),
            }),
        };
        return JsonSerializer.Serialize(doc, new JsonSerializerOptions { WriteIndented = true });
    }

    // ---- helpers ----

    /// <summary>A filesystem-safe base name for the emitted recipe file.</summary>
    private static string FileBase(string controlId)
    {
        var invalid = Path.GetInvalidFileNameChars();
        var sb = new StringBuilder(controlId.Length);
        foreach (char c in controlId)
            sb.Append(Array.IndexOf(invalid, c) >= 0 || c == ' ' ? '_' : c);
        string b = sb.ToString().Trim();
        return b.Length == 0 ? "control" : b;
    }
}
